# Generated by Django 2.1.5 on 2019-02-27 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('acity', models.CharField(max_length=100)),
                ('astate', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'address_many',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=100)),
                ('eemail', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=15)),
                ('eage', models.IntegerField()),
                ('esalary', models.IntegerField()),
                ('eaddress', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'one_emp',
            },
        ),
        migrations.AddField(
            model_name='address',
            name='emp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_many_mapping.Employee'),
        ),
    ]
